/* This file was automatically generated by CasADi 3.7.1.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

extern "C" int f(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int f_alloc_mem(void);
extern "C" int f_init_mem(int mem);
extern "C" void f_free_mem(int mem);
extern "C" int f_checkout(void);
extern "C" void f_release(int mem);
extern "C" void f_incref(void);
extern "C" void f_decref(void);
extern "C" casadi_int f_n_in(void);
extern "C" casadi_int f_n_out(void);
extern "C" casadi_real f_default_in(casadi_int i);
extern "C" const char* f_name_in(casadi_int i);
extern "C" const char* f_name_out(casadi_int i);
extern "C" const casadi_int* f_sparsity_in(casadi_int i);
extern "C" const casadi_int* f_sparsity_out(casadi_int i);
extern "C" int f_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int f_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define f_SZ_ARG 5
#define f_SZ_RES 2
#define f_SZ_IW 0
#define f_SZ_W 6
extern "C" int df_dx(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int df_dx_alloc_mem(void);
extern "C" int df_dx_init_mem(int mem);
extern "C" void df_dx_free_mem(int mem);
extern "C" int df_dx_checkout(void);
extern "C" void df_dx_release(int mem);
extern "C" void df_dx_incref(void);
extern "C" void df_dx_decref(void);
extern "C" casadi_int df_dx_n_in(void);
extern "C" casadi_int df_dx_n_out(void);
extern "C" casadi_real df_dx_default_in(casadi_int i);
extern "C" const char* df_dx_name_in(casadi_int i);
extern "C" const char* df_dx_name_out(casadi_int i);
extern "C" const casadi_int* df_dx_sparsity_in(casadi_int i);
extern "C" const casadi_int* df_dx_sparsity_out(casadi_int i);
extern "C" int df_dx_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int df_dx_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define df_dx_SZ_ARG 3
#define df_dx_SZ_RES 2
#define df_dx_SZ_IW 0
#define df_dx_SZ_W 9
extern "C" int df_dw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int df_dw_alloc_mem(void);
extern "C" int df_dw_init_mem(int mem);
extern "C" void df_dw_free_mem(int mem);
extern "C" int df_dw_checkout(void);
extern "C" void df_dw_release(int mem);
extern "C" void df_dw_incref(void);
extern "C" void df_dw_decref(void);
extern "C" casadi_int df_dw_n_in(void);
extern "C" casadi_int df_dw_n_out(void);
extern "C" casadi_real df_dw_default_in(casadi_int i);
extern "C" const char* df_dw_name_in(casadi_int i);
extern "C" const char* df_dw_name_out(casadi_int i);
extern "C" const casadi_int* df_dw_sparsity_in(casadi_int i);
extern "C" const casadi_int* df_dw_sparsity_out(casadi_int i);
extern "C" int df_dw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int df_dw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define df_dw_SZ_ARG 5
#define df_dw_SZ_RES 2
#define df_dw_SZ_IW 4
#define df_dw_SZ_W 15
extern "C" int h(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int h_alloc_mem(void);
extern "C" int h_init_mem(int mem);
extern "C" void h_free_mem(int mem);
extern "C" int h_checkout(void);
extern "C" void h_release(int mem);
extern "C" void h_incref(void);
extern "C" void h_decref(void);
extern "C" casadi_int h_n_in(void);
extern "C" casadi_int h_n_out(void);
extern "C" casadi_real h_default_in(casadi_int i);
extern "C" const char* h_name_in(casadi_int i);
extern "C" const char* h_name_out(casadi_int i);
extern "C" const casadi_int* h_sparsity_in(casadi_int i);
extern "C" const casadi_int* h_sparsity_out(casadi_int i);
extern "C" int h_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int h_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define h_SZ_ARG 5
#define h_SZ_RES 2
#define h_SZ_IW 0
#define h_SZ_W 27
extern "C" int dh_dx(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int dh_dx_alloc_mem(void);
extern "C" int dh_dx_init_mem(int mem);
extern "C" void dh_dx_free_mem(int mem);
extern "C" int dh_dx_checkout(void);
extern "C" void dh_dx_release(int mem);
extern "C" void dh_dx_incref(void);
extern "C" void dh_dx_decref(void);
extern "C" casadi_int dh_dx_n_in(void);
extern "C" casadi_int dh_dx_n_out(void);
extern "C" casadi_real dh_dx_default_in(casadi_int i);
extern "C" const char* dh_dx_name_in(casadi_int i);
extern "C" const char* dh_dx_name_out(casadi_int i);
extern "C" const casadi_int* dh_dx_sparsity_in(casadi_int i);
extern "C" const casadi_int* dh_dx_sparsity_out(casadi_int i);
extern "C" int dh_dx_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int dh_dx_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define dh_dx_SZ_ARG 5
#define dh_dx_SZ_RES 2
#define dh_dx_SZ_IW 4
#define dh_dx_SZ_W 55
extern "C" int dh_dv(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int dh_dv_alloc_mem(void);
extern "C" int dh_dv_init_mem(int mem);
extern "C" void dh_dv_free_mem(int mem);
extern "C" int dh_dv_checkout(void);
extern "C" void dh_dv_release(int mem);
extern "C" void dh_dv_incref(void);
extern "C" void dh_dv_decref(void);
extern "C" casadi_int dh_dv_n_in(void);
extern "C" casadi_int dh_dv_n_out(void);
extern "C" casadi_real dh_dv_default_in(casadi_int i);
extern "C" const char* dh_dv_name_in(casadi_int i);
extern "C" const char* dh_dv_name_out(casadi_int i);
extern "C" const casadi_int* dh_dv_sparsity_in(casadi_int i);
extern "C" const casadi_int* dh_dv_sparsity_out(casadi_int i);
extern "C" int dh_dv_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int dh_dv_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define dh_dv_SZ_ARG 4
#define dh_dv_SZ_RES 2
#define dh_dv_SZ_IW 4
#define dh_dv_SZ_W 15
